// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService is bound to the Wails frontend (see application.NewService
 * in albiondata-client.go). Its methods back-fill the dashboard window's
 * state when it's shown; ongoing updates arrive via the "status:changed",
 * "counters:snapshot", and "log:line" events instead.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRecentLogs returns the currently buffered recent log lines.
 * @returns {$CancellablePromise<$models.LogLine[]>}
 */
export function GetRecentLogs() {
    return $Call.ByID(660391799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStartupEnabled reports whether the logon task is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetStartupEnabled() {
    return $Call.ByID(927544449);
}

/**
 * GetStatus returns the current status snapshot.
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(1612471225).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetUploadCounts returns the current upload counters by topic.
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetUploadCounts() {
    return $Call.ByID(1683242014).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetStartupEnabled changes the logon task, prompting for UAC consent if
 * the app was launched without administrator privileges.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<boolean>}
 */
export function SetStartupEnabled(enabled) {
    return $Call.ByID(1663975629, enabled);
}

/**
 * StartupSupported reports whether the Windows logon task is available.
 * @returns {$CancellablePromise<boolean>}
 */
export function StartupSupported() {
    return $Call.ByID(2743038392);
}

// Private type creation functions
const $$createType0 = $models.LogLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Status.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
