// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogLine is one captured log entry, formatted for display.
 */
export class LogLine {
    /**
     * Creates a new LogLine instance.
     * @param {Partial<LogLine>} [$$source = {}] - The source object to create the LogLine.
     */
    constructor($$source = {}) {
        if (!("Time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Time"] = "";
        }
        if (!("Level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Level"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLine(/** @type {Partial<LogLine>} */($$parsedSource));
    }
}

/**
 * Status is a point-in-time snapshot of the client's observable state,
 * pushed to the dashboard frontend whenever it changes.
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("UpdateAvailable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdateAvailable"] = "";
        }
        if (!("CaptureRunning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CaptureRunning"] = false;
        }
        if (!("CaptureError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CaptureError"] = false;
        }
        if (!("ServerID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ServerID"] = 0;
        }
        if (!("IngestBaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IngestBaseURL"] = "";
        }
        if (!("CustomPublicIngest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["CustomPublicIngest"] = false;
        }
        if (!("DriverWarning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DriverWarning"] = "";
        }
        if (!("DriverHelpURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DriverHelpURL"] = "";
        }
        if (!("EncryptionStatus" in $$source)) {
            /**
             * EncryptionStatus is "" (unknown - nothing observed yet this
             * session), "encrypted" (a market data response came back
             * encrypted), or "clear" (a market data response came back and
             * decoded normally). See client/albion_state.go's
             * ShouldNotifyMarketDataEncrypted for how "encrypted" is decided.
             * @member
             * @type {string}
             */
            this["EncryptionStatus"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}
